### ISSUE TITLE
Build error!

### ISSUE THREAD

**Issue by PratikGajera** [CatalystApps/libboost#1]
Dear CatalystApps,

I am building your given source code of libboost on my ubuntu 14.04 system. I run the below command and  getting error:
$ ${NDK_PATH}/ndk-build

[armeabi-v7a] Compile++ thumb: boost_static <= file_descriptor.cpp
[armeabi-v7a] Compile++ thumb: boost_static <= gzip.cpp
[armeabi-v7a] Compile++ thumb: boost_static <= mapped_file.cpp
[armeabi-v7a] Compile++ thumb: boost_static <= zlib.cpp
[armeabi-v7a] Compile++ thumb: boost_static <= archive_exception.cpp
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:18:9: warning: 'BOOST_ARCHIVE_SOURCE'
      macro redefined [-Wmacro-redefined]
#define BOOST_ARCHIVE_SOURCE
        ^
<command line>:6:9: note: previous definition is here
#define BOOST_ARCHIVE_SOURCE 1
        ^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:36:1: error: unknown type name
      'BOOST_ARCHIVE_DECL'
BOOST_ARCHIVE_DECL 
^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:37:20: error: constructor cannot have a
      return type
archive_exception::archive_exception(
                   ^~~~~~~~~~~~~~~~~
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:42:10: error: use of undeclared
      identifier 'c'
    code(c)
         ^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:45:12: error: use of undeclared
      identifier 'code'
    switch(code){
           ^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:112:1: error: unknown type name
      'BOOST_ARCHIVE_DECL'
BOOST_ARCHIVE_DECL
^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:115:1: error: unknown type name
      'BOOST_ARCHIVE_DECL'
BOOST_ARCHIVE_DECL const char *
^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:115:20: error: expected unqualified-id
BOOST_ARCHIVE_DECL const char *
                   ^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:119:1: error: unknown type name
      'BOOST_ARCHIVE_DECL'
BOOST_ARCHIVE_DECL
^
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:120:20: error: constructor cannot have a
      return type
archive_exception::archive_exception() BOOST_NOEXCEPT :
                   ^~~~~~~~~~~~~~~~~
/home/test/NDK/android-ndk-r13b/libboost/jni/../src/boost/libs/serialization/src/archive_exception.cpp:121:10: error: use of undeclared
      identifier 'no_exception'; did you mean 'archive_exception::no_exception'?
    code(no_exception)
         ^~~~~~~~~~~~
         archive_exception::no_exception
/usr/include/boost/archive/archive_exception.hpp:50:9: note: 'archive_exception::no_exception' declared here
        no_exception,       // initialized without code
        ^
1 warning and 10 errors generated.
make: *** [/home/test/NDK/android-ndk-r13b/libboost/obj/local/armeabi-v7a/objs/boost_static/__/src/boost/libs/serialization/src/archive_exception.o] Error 1

**Comment by SmartCat** [comment]
Hello!
Sorry, but this is fork for internal project usage.
Please use official one instead.

Kind regards

**Comment by PratikGajera** [comment]
Thanks for your reply!
Can you provides link which help for me?
